name: Run iPerf3 Check and Update README

on:
  workflow_dispatch:
  schedule:
    - cron: '25 4 * * *'
  push:
    paths:
      - 'readme-header.md'
      - 'list.yml'
      - 'check-iperf3.py'
      - 'Dockerfile'
      - '.github/workflows/run-iperf3.yml'
jobs:
  run-iperf3-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Build Docker image
        run: docker build -t iperf3-check .

      - name: Run the check
        run: docker run --name iperf3-runner iperf3-check

      - name: Copy README.md from container
        run: docker cp iperf3-runner:/README.md README.md

      - name: Set up Git user
        run: |
          git config --global user.name "iperf3-checker-bot"
          git config --global user.email "iperf3-checker-bot@itdog.info"

      - name: Commit and push if README.md changed
        run: |
          git add README.md
          git diff --cached --quiet || git commit -m "Update from the bot"
          git push
